/usr/bin/python3 \
/usr/bin/s3vaultfuse.py \
--config-file=/etc/triliovault-datamover/triliovault-datamover.conf
